### ISSUE TITLE
Layertype Setting

### ISSUE THREAD

**Issue by DerfJagged** [Liggy/binflash#1]
Thank you for the great tool, I was able to flash my drive!

I was curious if it was possible to change the "layer type" that a drive burns a DVD+R as. When I burn an ISO to disc, it is "Layer Type: Recordable" before and after the burn, but when my friend burns the same ISO to another disc in the same spindle with his DVD drive, it becomes "Layer Type: Read-only" afterwards. A device I am using requires read-only layer types, so it'd be great to flash my drive with a modified firmware to enforce this layer type.

I am using a Sony NEC Optiarc Optiarc AD-7200S.

**Comment by Liggy** [comment]
I assume you want to set the booktype from DVD+R to DVD-ROM. For this you only need a firmware that supports bitsetting and with Binflash you need to change the booktype for DVD+R to DVD-ROM.

**Comment by DerfJagged** [comment]
> 
> 
> I assume you want to set the booktype from DVD+R to DVD-ROM. For this you only need a firmware that supports bitsetting and with Binflash you need to change the booktype for DVD+R to DVD-ROM.

Thanks for the reply!  Layer type is similar - but separate - from booktype. I actually flashed a firmware to allow bitsetting to DVD-ROM. [Layer type is a different field that marks a disc as Read-Only, Recordable, or Rewriteable](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddcdvd/ns-ntddcdvd-_dvd_layer_descriptor). While it seems very rare that devices require layer type to be set to Read-Only, there definitely are some out there like car navigation systems or Xbox. 

It seems to me by [this thread](https://forum.imgburn.com/index.php?/topic/23398-does-imgburn-support-setting-layer-type-continued/) that it could maybe be set via firmware modification. Any chance that you could incorporate this? I'm not sure how to properly form a command to send to the drive to set this.

**Comment by Liggy** [comment]
As discussed on the myce.com forum, this is probably nothing I could easily add. It will probably require firmware modifications that are not related to Binflash.
