### ISSUE TITLE
LayerType Setting

### ISSUE THREAD

**Issue by DerfJagged** [Liggy/binflash#11]
Is there any possibility of adding the ability to change the LayerType (not BookType) that discs are burned as? 

If you aren't aware, LayerType is the second byte burned to a disc. 99% of burners seem to burn discs with LayerType set to "recordable" (0x2) and not "read-only" (0x1), and it seems to be a factory error that burners were released that will burn them as "read-only". Almost no software actually cares about or requires this byte set to read-only, but these are some cases I'm aware of:
* [Navigation maps update discs for Audi cars](https://www.ttforum.co.uk/threads/imburn-rns-e-2018-map-update.1847605/)
* [Xbox and Xbox 360 to run special DVD movie demo software, including a DVD-specific dashboard](https://consolemods.org/wiki/Xbox:DVD_Movies_with_Xbox_Demos)

There are probably more use cases out there, most likely just chalked up to some other issue since this seems to be a very obscure security feature. Details, including a program to check what a disc was burned as, can be found in the first link.

On an unrelated note, I saw you have backed up the CDFreaks/MyCE forums. Have you made any further attempts to get them running? It was an incredible resource, and definitely deserves to be restored - at least in a read-only state. I left a message about this on the ConfusedBird forum, but figured I'd ask here in case you didn't get notified.

**Comment by Liggy** [comment]
Sorry, but I don't think I'll be able to change the LayerType of a disc. My last work on firmware was done some years ago and recalling all the knowledge would require a lot of time that I would not want to spend on something that only very few people still care about - even then I doubt that I'd be able to locate that place inside the firmware which is responsible for setting the LayerType.

Regarding the backup, I just replied on the ConfuesedBird forum.
