### ISSUE TITLE
Error submitting checksum on Optiarc 5280S

### ISSUE THREAD

**Issue by jdev15** [Liggy/binflash#3]
When using Binflash 1.64 and trying to flash the latest firmware 1.g8 I get checksum error. My drive is currently on 1.01, and I don't know why the program is throwing this error.

**Comment by Liggy** [comment]
The error either comes from a corrupt firmware file (5280S firmware should be 1.769.480 Bytes) or the SATA controller that your drive is attached to is incompatible with the command for sending a checksum to the drive. What exact checksum error do you get?

**Comment by jdev15** [comment]
I'm using the firmware from the archive you've linked in the README.MD (specifically 1g8bt_orig.bin, but I also tried 1g8_orig). My motherboard is the MSI B350 PC Mate and the exact error it throws is: "Error submiting checksum"
It's weird, because I've even tried connecting the DVD drive through my SATA to USB adapter I have and it gave me the same error.

**Comment by Liggy** [comment]
I added my cheksum tool to the release. If you're familiar with the command line, you can check if the firmware checksums are OK. In that case your hardware seems to be incompatible with the command required for sending the checksum to your drive and you'd have to try a different PC.
If the checksums are not OK then you need to re-download or extract with a different tool. I downloaded the archive and the 1.g8 firmware was OK.

You could also try to dump your current firmware and flash it back. If that doesn't work, it's an issue with your PC.

**Comment by jdev15** [comment]
I've tested on an old Pentium 4 rig with SATA where reflashing the existing firmware works, and it gives me the same error when trying to flash the 1.g8 firmware. The checksum tool also seems to report no errors. In particular, with the drive's firmware it reports:
`Inner Chksum 1:
Found: a3 - 20
Expected: a3 - 20
Chksum 1:
Found: 88 - c8
Expected: 88 - c8`
And with the various versions of the 1.g8 firmware it reports:
`Inner Chksum 1:
Found: 9b - 8d
Expected: 9b - 8d
Chksum 1:
Found: 15 - 0c
Expected: 15 - 0c`

**Comment by Liggy** [comment]
I just noticed (forgot about it) that there are two different drive revisions that identify as AD-5280S. Unfortunately firmwares for these drives are not compatible, so you probably won't be able to flash.
I just wonder why you only get the error that late. If I remember correctly, Binflash should already report much earlier that the given firmware is for a different drive.

**Comment by jdev15** [comment]
Uh, didn't know about the different revisions. Do you know where I can find the latest firmware specific to my revision? It's odd, because I remember flashing a modified version of v1.01 way back when to support setting the booktype.

**Comment by Liggy** [comment]
You might try asking in the [Myce NEC / Optiarc Forum](https://club.myce.com/c/cd-dvd-and-blu-ray-writers/nec-optiarc-writer/58), if someone still has firmwares that I did not include in my archive, but I cannot help further I think.
