### ISSUE TITLE
Building on Mac OS X fails due to PowerPC build requirement

### ISSUE THREAD

**Issue by programmingkidx** [Liggy/binflash#4]
I am building on Mac OS 10.4 (x86) using gcc 7. The problem I excountered was with having to build a PowerPC binary along with the x86 binary. I think it would be best to add a couple of new targets to the makefile. These are what come to mind:
mac-intel
mac-powerpc
universal-binary
mac-arm  <--- possible future target

Adding binaries of binflash for download would make things very convenient for the user.

**Comment by Liggy** [comment]
I'm not planning to spend much time on updating Binflash as the current version should support most of the compatible hardware and new hardware is not to be expected. Feel free to work on your on requirements as per your needs, but don't expect me to provide too much support - in particular on Mac platform.

Binaries for download can be found under [Releases](https://github.com/Liggy/binflash/releases).
