### ISSUE TITLE
Request support for LG GDR-8163b.

### ISSUE THREAD

**Issue by ableto288** [Liggy/binflash#6]
Hello, i have just discover this tool and i have seen than is the best nowadays. I would like support fot LG-GDR 8163b, it would help to everybody that have a xbox classic and need to change the original dvd drive and avoiding the need of use an old dos program.

Thanks for your work, and sorry for my bad english.

**Comment by Liggy** [comment]
Sorry, Binflash was explicitly written for burners with NEC / Optiarc architecture. LG drives will probably have to be flashed in an entirely different way and I've got no information on how to access these drives' firmware or if that kind of access is even possible.
