### ISSUE TITLE
Firmware Mirror

### ISSUE THREAD

**Issue by disc-kuraudo** [Liggy/binflash#7]
Hi,

this not a direct issue related to binflash.

I'm looking for some firmwares from liggydee.cdfreaks.com. archive.org doesn't have a complete backup, some firmwares are missing.

Specifically the 3APE "fast" firmware for AD-5970H doesn't seem to work for me for DVD-Video, the other 2 listed firmwares I'd like to try are not backed up on archive.org. I even tried to rename the `VIDEO_TS` occurence in the firmware blob to `FASTFAST` like I've seen in other vendors' firmwares and recalculate the checksum, still getting 2X on DVD-Video, 4X on DVD-ROM discs.

If you could maybe re-upload them firmwares to e.g. archive.org if you still have them, would be very grateful.

Thanks. Great toolset btw.

**Comment by liggy1** [comment]
All the firmwares that I still had were uploaded to OneDrive and linked to on the main project page. For the AD-5970H firmwares 3APE and two versions of 3APH are available. You can try these, but that's all I have.

**Comment by disc-kuraudo** [comment]
Oh, I completely overlooked that section.

Downloaded it, thanks a lot.

Tried both other 3APH fast firmwares, seems to be still 2X for DVD-Video (even on DVD-Rs, not even limited to CSS cucked DVD-Video discs) will have to see if I can somehow pin down the cucking mechanism with experimenting with burning some DVD-Rs with/without a DVD-Video structure on them.
