### ISSUE TITLE
AD-7585H support

### ISSUE THREAD

**Issue by marcus905** [Liggy/binflash#8]
Hi, what should I do to add support to this drive? I need to recover a drive that has corrupted firmware by dumping one from a working drive if it's possible.

Thank you!

**Comment by liggy1** [comment]
Sorry, but the AD-7585H is based on a QSI design (QSI SDW-089B) and cannot be supported by Binflash. I am unaware of any other tools for these devices.

**Comment by Liggy** [comment]
Sorry, but the AD-7585H is based on a QSI design (QSI SDW-089B) and cannot be supported by Binflash. I am unaware of any other tools for these devices.

**Comment by marcus905** [comment]
That's too bad, but thanks!
